gender_map = {"male": 1, "female": 0, "Male": 1, "Female": 0}

# 国家映射：label为1且<2的国家映射到大洲
country_map = {
    # 原有映射
    "Austria": "Others",
    "Denmark": "Others_EU",
    "Hungary": "Others",
    "Israel": "Others",
    "Italy": "Others_EU",
    "Spain": "Others_EU",
    "Norway": "Others_EU",
    "Sweden": "Others_EU",
    "Switzerland": "Others_EU",
    "Singapore": "Others",
    "South Korea": "Others",
    "Netherlands": "Others",
    "Australia": "Others",
    # label为1且<2的国家映射到大洲
    # 欧洲国家 -> Others_EU
    "England": "United Kingdom",
    "Finland": "Others_EU",
    "Poland": "Others_EU",
    "Romania": "Others_EU",
    "Scotland": "Others_EU",
    "Turkey": "Others_EU",
    "Ukraine": "Others_EU",
    "Yugoslavia": "Others_EU",
    # 其他大洲 -> Others
    "Algeria": "Others",  # 非洲
    "Cuba": "Others",  # 北美洲
    "Jordan": "Others",  # 亚洲
    "Lebanon": "Others",  # 亚洲
    "Mexico": "Others",  # 北美洲
    "Morocco": "Others",  # 非洲
    "New Zealand": "Others",  # 大洋洲
    "South Africa": "Others",  # 非洲
    "Argentina": "Others",  # 南美洲
}

institution_mapping = {
    # Harvard
    "Harvard University": "Harvard University",
    "Harvard College": "Harvard University",
    "Harvard Medical School": "Harvard University",
    "Harvard Kennedy School": "Harvard University",
    "Harvard Graduate School of Education": "Harvard University",
    "Harvard Society of Fellows": "Harvard University",
    "Harvard Economics Department": "Harvard University",
    # MIT
    "Massachusetts Institute of Technology": "Massachusetts Institute of Technology",
    "MIT": "Massachusetts Institute of Technology",
    "M.I.T.": "Massachusetts Institute of Technology",
    "Massachusetts Institute of Technology (MIT)": "Massachusetts Institute of Technology",
    "MIT Sloan School of Management": "Massachusetts Institute of Technology",
    "MIT Center for Learning and Memory": "Massachusetts Institute of Technology",
    "MIT Center for Neurobiological Engineering": "Massachusetts Institute of Technology",
    "MIT McGovern Institute": "Massachusetts Institute of Technology",
    "MIT Koch Institute for Integrative Cancer Research": "Massachusetts Institute of Technology",
    "MIT Media Lab": "Massachusetts Institute of Technology",
    "MIT Lincoln Laboratory": "Massachusetts Institute of Technology",
    "MIT Kavli Institute for Astrophysics and Space Research": "Massachusetts Institute of Technology",
    "MIT Center for Ultracold Atoms": "Massachusetts Institute of Technology",
    "MIT-Harvard Center for Ultracold Atoms": "Massachusetts Institute of Technology",
    "Massachusetts Institute of Technology (Research Laboratory of Electronics)": "Massachusetts Institute of Technology",
    "Research Laboratory of Electronics (RLE)": "Massachusetts Institute of Technology",
    # UC Berkeley
    "University of California, Berkeley": "University of California, Berkeley",
    "UC Berkeley": "University of California, Berkeley",
    "University of California at Berkeley": "University of California, Berkeley",
    "Berkeley": "University of California, Berkeley",
    "Lawrence Berkeley National Laboratory": "University of California, Berkeley",
    "Lawrence Berkeley Laboratory": "University of California, Berkeley",
    "Berkeley Global Science Institute": "University of California, Berkeley",
    "Haas School of Business": "University of California, Berkeley",
    "Haas School of Business, University of California, Berkeley": "University of California, Berkeley",
    # Stanford
    "Stanford University": "Stanford University",
    "Stanford Hospital and Clinics": "Stanford University",
    "Stanford University School of Medicine": "Stanford University",
    "Stanford Graduate School of Business": "Stanford University",
    "Stanford University School of Engineering": "Stanford University",
    "Stanford University Department of Chemistry": "Stanford University",
    "Stanford Sleep Center": "Stanford University",
    "Stanford Center for Sleep Sciences and Medicine": "Stanford University",
    "Stanford Medical School, Stanford University": "Stanford University",
    "Stanford Linear Accelerator Center": "Stanford University",
    "SLAC": "Stanford University",
    # Princeton
    "Princeton University": "Princeton University",
    "Princeton Center for Theoretical Science": "Princeton University",
    "Princeton School of Public and International Affairs": "Princeton University",
    "Princeton Day School": "Princeton University",
    "Institute for Advanced Study": "Princeton University",
    "Institute for Advanced Study, Princeton": "Princeton University",
    # University of Chicago
    "University of Chicago": "University of Chicago",
    "University of Chicago Booth School of Business": "University of Chicago",
    "University of Chicago Law School": "University of Chicago",
    # Yale
    "Yale University": "Yale University",
    "Yale School of Medicine": "Yale University",
    "Yale School of Management": "Yale University",
    # Columbia
    "Columbia University": "Columbia University",
    "Columbia College": "Columbia University",
    "Columbia University College of Physicians and Surgeons": "Columbia University",
    "Columbia University Medical Center": "Columbia University",
    "Columbia University School of Engineering and Applied Science": "Columbia University",
    "Columbia University Irving Medical Center": "Columbia University",
    # Cambridge
    "University of Cambridge": "University of Cambridge",
    "Cambridge": "University of Cambridge",
    "Cambridge University": "University of Cambridge",
    "Trinity College, Cambridge": "University of Cambridge",
    "Clare Hall, Cambridge": "University of Cambridge",
    "Christ's College, Cambridge": "University of Cambridge",
    "Clare College, Cambridge": "University of Cambridge",
    "Churchill College, Cambridge": "University of Cambridge",
    "Fitzwilliam College, Cambridge": "University of Cambridge",
    "Gonville & Caius College, Cambridge": "University of Cambridge",
    "Jesus College, Cambridge": "University of Cambridge",
    "King's College, Cambridge": "University of Cambridge",
    "Peterhouse, Cambridge": "University of Cambridge",
    "Sidney Sussex College, Cambridge": "University of Cambridge",
    "St John's College, Cambridge": "University of Cambridge",
    "Cavendish Laboratory, University of Cambridge": "University of Cambridge",
    "Department of Applied Mathematics and Theoretical Physics, Cambridge": "University of Cambridge",
    "MRC Laboratory of Molecular Biology, Cambridge": "University of Cambridge",
    # Oxford
    "University of Oxford": "University of Oxford",
    "Oxford University": "University of Oxford",
    "Oxford": "University of Oxford",
    "Balliol College, Oxford": "University of Oxford",
    "Balliol College, Oxford University": "University of Oxford",
    "Green Templeton College, Oxford": "University of Oxford",
    "Magdalen College School, Oxford": "University of Oxford",
    "Merton College, Oxford": "University of Oxford",
    "Merton College, Oxford University": "University of Oxford",
    "New College, Oxford": "University of Oxford",
    "Nuffield College, Oxford": "University of Oxford",
    "Somerville College, Oxford": "University of Oxford",
    "St Catherine's College, Oxford": "University of Oxford",
    "University of Oxford (Magdalen College)": "University of Oxford",
    "University of Oxford (Merton College)": "University of Oxford",
    "University of Oxford, St Catherine's College": "University of Oxford",
    "Clarendon Laboratory, University of Oxford": "University of Oxford",
    "Mathematical Institute, University of Oxford": "University of Oxford",
    # Caltech
    "California Institute of Technology": "California Institute of Technology",
    "Caltech": "California Institute of Technology",
    # Cornell
    "Cornell University": "Cornell University",
    # Penn
    "University of Pennsylvania": "University of Pennsylvania",
    "University of Pennsylvania School of Medicine": "University of Pennsylvania",
    "University of Pennsylvania Faculty of Arts and Sciences": "University of Pennsylvania",
    "Wharton School of the University of Pennsylvania": "University of Pennsylvania",
    # UC
    "University of California, San Francisco": "University of California, San Francisco",
    "UCSF": "University of California, San Francisco",
    "University of California San Francisco": "University of California, San Francisco",
    "UCSF Sloan Center for Theoretical Neuroscience": "University of California, San Francisco",
    "University of California, San Diego": "University of California, San Diego",
    "UCSD": "University of California, San Diego",
    "Scripps Institution of Oceanography, University of California, San Diego": "University of California, San Diego",
    "University of California, Los Angeles": "University of California, Los Angeles",
    "UCLA": "University of California, Los Angeles",
    "University of California, Santa Barbara": "University of California, Santa Barbara",
    "Institute for Theoretical Physics, UC Santa Barbara": "University of California, Santa Barbara",
    "University of California, Davis": "University of California, Davis",
    "University of California, Santa Cruz": "University of California, Santa Cruz",
    "University of California at Santa Cruz": "University of California, Santa Cruz",
    "Lick Observatory, University of California, Santa Cruz": "University of California, Santa Cruz",
    "University of California, Irvine": "University of California, Irvine",
    "University of California, Irvine School of Medicine": "University of California, Irvine",
    # Japanese Universities
    "Kyoto University": "Kyoto University",
    "京都大学": "Kyoto University",
    "Kyoto University School of Medicine": "Kyoto University",
    "Department of Medical Chemistry, Kyoto University Faculty of Medicine": "Kyoto University",
    "Department of Immunology and Genomic Medicine, Kyoto University Faculty of Medicine": "Kyoto University",
    "Kyoto University, Research Institute for Fundamental Physics": "Kyoto University",
    "Kyoto University, Faculty of Science": "Kyoto University",
    "Yukawa Institute for Theoretical Physics, Kyoto University": "Kyoto University",
    "Institute for Frontier Medical Sciences, Kyoto University": "Kyoto University",
    "Center for iPS Cell Research and Application (CiRA), Kyoto University": "Kyoto University",
    "University of Tokyo": "University of Tokyo",
    "Faculty of Medicine, University of Tokyo": "University of Tokyo",
    "Institute of Medical Science, University of Tokyo": "University of Tokyo",
    "University of Tokyo, Institute for Nuclear Study": "University of Tokyo",
    # Other Universities
    "Hebrew University of Jerusalem": "Hebrew University of Jerusalem",
    "Hebrew University": "Hebrew University of Jerusalem",
    "Interdisciplinary Center for Neural Computation, Hebrew University": "Hebrew University of Jerusalem",
    "London School of Economics": "London School of Economics",
    "London School of Economics and Political Science": "London School of Economics",
    "London School of Economics and School for Advanced Studies in the Social Sciences (joint)": "London School of Economics",
    "Imperial College London": "Imperial College London",
    "Imperial College, London": "Imperial College London",
    # Research Institutes
    "Howard Hughes Medical Institute": "Howard Hughes Medical Institute",
    "Howard Hughes Medical Institute, University of Utah": "Howard Hughes Medical Institute",
    "Howard Hughes Medical Institute Scientific Review Board": "Howard Hughes Medical Institute",
    "Bell Labs": "Bell Labs",
    "AT&T Bell Laboratories": "Bell Labs",
    "Bell Labs, Lucent Technologies": "Bell Labs",
    "Rockefeller University": "Rockefeller University",
    "The Rockefeller University": "Rockefeller University",
    "Weizmann Institute of Science": "Weizmann Institute of Science",
    "National Bureau of Economic Research": "National Bureau of Economic Research",
    "National Bureau of Economic Research (NBER)": "National Bureau of Economic Research",
    "National Bureau of Economic Research, Development of the American Economy program": "National Bureau of Economic Research",
    "National Institutes of Health": "National Institutes of Health",
    "NIH": "National Institutes of Health",
    "National Cancer Institute": "National Institutes of Health",
    "National Human Genome Research Institute": "National Institutes of Health",
    "National Eye Institute, National Institute of Health": "National Institutes of Health",
    "Laboratory of Sensorimotor Research, National Eye Institute, National Institute of Health": "National Institutes of Health",
    "National Institute of Child Health and Human Development, NIH": "National Institutes of Health",
    # Max Planck Institutes - grouped into one organization
    "Max Planck Institute of Biochemistry": "Max Planck Society",
    "Max Planck Institute for Quantum Optics": "Max Planck Society",
    "Max Planck Institute of Quantum Optics": "Max Planck Society",
    "Max Planck Institute for Biophysical Chemistry": "Max Planck Society",
    "Max Planck Institute for Biophysical Chemistry (now Multidisciplinary Sciences), Göttingen": "Max Planck Society",
    "Max Planck Institute of Biophysical Chemistry": "Max Planck Society",
    "Max Planck Institute of Biophysical Chemistry (now Multidisciplinary Sciences)": "Max Planck Society",
    "Max Planck Institute for Multidisciplinary Sciences": "Max Planck Society",
    "Max Planck Institute for Medical Research, Heidelberg": "Max Planck Society",
    "Max Planck Institute of Metals Research": "Max Planck Society",
    "Max Planck Institute for Metals Research": "Max Planck Society",
    "Max Planck Institute for Solid State Research": "Max Planck Society",
    "Max Planck Institute for Solid State Research, Stuttgart": "Max Planck Society",
    "Max Planck Institute of Microstructure Physics": "Max Planck Society",
    "Max Planck Institute for Chemistry": "Max Planck Society",
    "Max Planck Institute for Evolutionary Anthropology": "Max Planck Society",
    "Max Planck Institute for Astrophysics": "Max Planck Society",
    "Max Planck Institute of Immunobiology and Epigenetics": "Max Planck Society",
    "Max Planck Institute for Coal Research": "Max Planck Society",
    "Max Planck Society, Lorenz Institute for Behavioral Physiology in Buldern": "Max Planck Society",
    "Max Planck Institute for Behavioral Physiology in Seewiesen": "Max Planck Society",
    # Backwards compatibility with data
    "Unknown": "Unknown",
    "Italy": "Unknown",
    "Cameroon": "Unknown",
    "France (unspecified institution)": "Unknown",
    "UK institution (unnamed)": "Unknown",
}

institution_onehot = [
    "Massachusetts Institute of Technology",
    "Harvard University",
    "University of California, Berkeley",
    "Stanford University",
    "Princeton University",
    "University of Cambridge",
    "University of Chicago",
    "University of Oxford",
    "Howard Hughes Medical Institute",
    "Yale University",
    "Columbia University",
    "Max Planck Society",
    "California Institute of Technology",
    "Cornell University",
    "Kyoto University",
    "University of Pennsylvania",
    "University of California, San Francisco",
    "University of California, San Diego",
    "National Institutes of Health",
    "Bell Labs",
    "Hebrew University of Jerusalem",
    "University of Tokyo",
    "University of California, Los Angeles",
    "American Economic Association",
    "National Bureau of Economic Research",
    "London School of Economics",
    "University of Michigan",
    "Rockefeller University",
    "Imperial College London",
    "University of Rochester",
    "Unknown",
    "University of Toronto",
    "Technical University of Munich",
    "Duke University",
    "Brown University",
    "University of Paris",
    "University of Colorado Boulder",
    "Carnegie Mellon University",
    "University of Copenhagen",
    "University of Virginia",
    "Johns Hopkins School of Medicine",
    "Johns Hopkins University",
    "Northwestern University",
    "Nagoya University",
    "University College London",
    "University of Minnesota",
    "University of Washington",
    "University of Siena",
    "Salk Institute for Biological Studies",
    "École Normale Supérieure",
    "University of Southern California",
    "Econometric Society",
    "National University of Singapore",
    "Queen's University",
    "New York University",
    "University of California, Santa Barbara",
    "University of Heidelberg",
    "Collège de France",
    "Texas A&M University",
    "Brandeis University",
    "University of California, Santa Cruz",
    "Osaka University",
    "University of Göttingen",
    "University of Texas Southwestern Medical Center",
    "Scripps Research Institute",
    "International Monetary Fund",
    "University of London",
    "University of Texas at Austin",
    "Hokkaido University",
    "Utrecht University",
    "Ludwig Maximilian University of Munich",
    "National Taiwan University",
    "Dimensional Fund Advisors",
    "Paris School of Economics",
    "University of California, Davis",
    "Santa Fe Institute",
    "Royal Society",
    "Tohoku University",
    "State University of New York at Buffalo",
    "McGill University",
    "University of Manchester",
    "City College of New York",
    "Phillips Exeter Academy",
    "Weizmann Institute of Science",
    "École normale supérieure",
    "Moscow Institute of Physics and Technology",
    "Case Western Reserve University",
    "University of Science and Technology of China",
    "Goethe University Frankfurt",
    "University of Arizona",
    "University of British Columbia",
    "Washington University in St. Louis",
    "Pierre and Marie Curie University",
    "Los Alamos National Laboratory",
    "World Bank",
    "Williams College",
    "University of Illinois",
    "University of Bristol",
    "CERN",
    "King's College London",
    "University of Bonn",
    "American Finance Association",
    "Rice University",
    "University of Edinburgh",
    "Pennsylvania State University",
]
